default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: blog-test_development

test:
  <<: *default
  database: blog-test_test

production:
  <<: *default
  database: blog-test_production
  username: blog-test
  password: <%= ENV['BLOG-TEST_DATABASE_PASSWORD'] %>
